-- DataGuard compliance-framework schema (applied to Supabase project udlrihnuwfwndbpmxqtq).
-- Framework-agnostic; the Tanzania PDPA 2022 matrix is the first framework loaded.
-- Reference data only: public read-only via RLS. Seeded from db/supabase/seed-framework.sql
-- (generated by scripts/pdpa/gen-supabase-sql.mjs from scripts/pdpa-2022.source.mjs).

create table if not exists frameworks (
  code text primary key,
  name text not null,
  short_name text,
  jurisdiction text,
  status text,
  disclaimer text,
  created_at timestamptz default now()
);

create table if not exists framework_versions (
  framework_code text not null references frameworks(code) on delete cascade,
  version_code text not null,
  status text,
  act_number text,
  chapter text,
  gazette_reference text,
  commencement_date date,
  commencement_reference text,
  language_note text,
  matrix_version text,
  matrix_released date,
  primary key (framework_code, version_code)
);

create table if not exists framework_parts (
  framework_code text not null,
  version_code text not null,
  part_number text not null,
  part_title text not null,
  display_order int,
  primary key (framework_code, version_code, part_number),
  foreign key (framework_code, version_code) references framework_versions(framework_code, version_code) on delete cascade
);

create table if not exists framework_sections (
  framework_code text not null,
  version_code text not null,
  section_number text not null,
  part_number text not null,
  section_title text not null,
  display_order int,
  creates_obligation boolean default true,
  no_obligation_reason text,
  primary key (framework_code, version_code, section_number),
  foreign key (framework_code, version_code) references framework_versions(framework_code, version_code) on delete cascade
);

create table if not exists framework_requirements (
  framework_code text not null,
  version_code text not null,
  requirement_id text not null,
  part_number text,
  section_number text,
  provision text,
  requirement_title text,
  requirement_text text,
  primary key (framework_code, version_code, requirement_id),
  foreign key (framework_code, version_code) references framework_versions(framework_code, version_code) on delete cascade
);

create table if not exists framework_controls (
  framework_code text not null,
  version_code text not null,
  control_id text not null,
  requirement_id text,
  part_number text,
  section_number text,
  subsection text,
  paragraph text,
  legal_reference text,
  legal_requirement text,
  control_title text,
  control_description text,
  plain_language_question text,
  why_this_matters text,
  implementation_guidance text,
  expected_state text,
  response_type text,
  answer_options text[],
  required boolean,
  applicability text,
  applicability_question text,
  role_scope text,
  evidence_required text,
  evidence_examples text[],
  evidence_strength text,
  evidence_review_frequency text,
  risk_category text,
  default_risk_level text,
  risk_rationale text,
  remediation_guidance text,
  suggested_task text,
  suggested_task_priority text,
  control_status text,
  version text,
  source_type text,
  regulatory_status text,
  notes text,
  display_order int,
  primary key (framework_code, version_code, control_id),
  foreign key (framework_code, version_code) references framework_versions(framework_code, version_code) on delete cascade
);

create index if not exists idx_controls_section on framework_controls (framework_code, version_code, section_number);
create index if not exists idx_requirements_section on framework_requirements (framework_code, version_code, section_number);

-- Reference data: world-readable, no public write. Seeding uses a privileged channel.
alter table frameworks enable row level security;
alter table framework_versions enable row level security;
alter table framework_parts enable row level security;
alter table framework_sections enable row level security;
alter table framework_requirements enable row level security;
alter table framework_controls enable row level security;

create policy "public read frameworks" on frameworks for select to anon, authenticated using (true);
create policy "public read framework_versions" on framework_versions for select to anon, authenticated using (true);
create policy "public read framework_parts" on framework_parts for select to anon, authenticated using (true);
create policy "public read framework_sections" on framework_sections for select to anon, authenticated using (true);
create policy "public read framework_requirements" on framework_requirements for select to anon, authenticated using (true);
create policy "public read framework_controls" on framework_controls for select to anon, authenticated using (true);
